version: '3.7'

services:
  app:
    # This will build the image from the Dockerfile in the current directory
    build: .
    # You can also use the image from Docker Hub if you prefer
    # image: your-dockerhub-username/your-nodejs-app-name

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:8080" # Exposes NGINX on port 80 to the outside world
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
